// Pussy888 image mapping: source filename → { slug, title, category, tags, rtp }
// Identified from user-provided thumbnail screenshots (imgi_21 through imgi_215).
// Categories: slot | live | fish. Uncertain identifications flagged with `check: true`.

export const PUSSY888_MAPPING = [
  { src: 'imgi_21_4185.png', slug: 'primal-megaways', title: 'Primal Megaways', category: 'slot', tags: ['megaways', 'prehistoric'], rtp: 96.7 },
  { src: 'imgi_22_4188.png', slug: 'beat-the-beast', title: 'Beat the Beast', category: 'slot', tags: ['kraken', 'big-win'], rtp: 96.3 },
  { src: 'imgi_23_4187.png', slug: 'big-god-of-wealth', title: 'Big God of Wealth', category: 'slot', tags: ['angpao', 'asian'], rtp: 96.8 },
  { src: 'imgi_24_4186.png', slug: 'great-ming', title: 'Great Ming', category: 'slot', tags: ['asian', 'dynasty'] },
  { src: 'imgi_25_4199.png', slug: 'boo-phoenix', title: 'Boo Phoenix', category: 'slot', tags: ['phoenix', 'mythology'] },
  { src: 'imgi_26_4233.png', slug: 'midas-golden-touch', title: 'Midas Golden Touch', category: 'slot', tags: ['mythology', 'gold'] },
  { src: 'imgi_27_4189.png', slug: 'tigers-glory', title: 'Tigers Glory', category: 'slot', tags: ['tiger', 'big-win'] },
  { src: 'imgi_28_4214.png', slug: 'neptune-treasure', title: 'Neptune Treasure', category: 'slot', tags: ['ocean', 'mythology'] },
  { src: 'imgi_29_4195.png', slug: 'fortune-lions', title: 'Fortune Lions', category: 'slot', tags: ['asian', 'angpao'] },
  { src: 'imgi_30_4190.png', slug: 'roaring-wilds', title: 'Roaring Wilds', category: 'slot', tags: ['bear', 'wild'] },
  { src: 'imgi_31_4197.png', slug: 'arctic-treasure', title: 'Arctic Treasure', category: 'slot', tags: ['ice', 'adventure'] },
  { src: 'imgi_32_4211.png', slug: 'cat-queen', title: 'Cat Queen', category: 'slot', tags: ['egypt', 'mythology'] },
  { src: 'imgi_33_4201.png', slug: 'white-king', title: 'White King', category: 'slot', tags: ['lion', 'wild'] },
  { src: 'imgi_34_4286.png', slug: 'great-blue', title: 'Great Blue', category: 'slot', tags: ['ocean', 'big-win', 'free-spin'], rtp: 96.5 },
  { src: 'imgi_35_4288.png', slug: 'dolphin-reef', title: 'Dolphin Reef', category: 'slot', tags: ['ocean', 'free-spin'], rtp: 96.1 },
  { src: 'imgi_36_4193.png', slug: 'archer', title: 'Archer', category: 'slot', tags: ['adventure', 'classic'] },
  { src: 'imgi_37_4200.png', slug: 'buffalo-blitz', title: 'Buffalo Blitz', category: 'slot', tags: ['wild', 'big-win'] },

  { src: 'imgi_38_4289.png', slug: 'golden-tour', title: 'Golden Tour', category: 'slot', tags: ['sports', 'classic'], rtp: 95.3 },
  { src: 'imgi_39_4294.png', slug: 'highway-kings', title: 'Highway Kings', category: 'slot', tags: ['truck', 'classic'], rtp: 95.2 },
  { src: 'imgi_40_4308.png', slug: 'captain', title: 'Captain', category: 'slot', tags: ['pirate', 'adventure'] },
  { src: 'imgi_41_4296.png', slug: 'easter-surprise', title: 'Easter Surprise', category: 'slot', tags: ['holiday', 'bonus'] },
  { src: 'imgi_42_4249.png', slug: 'halloween-party', title: 'Halloween Party', category: 'slot', tags: ['halloween', 'holiday'] },
  { src: 'imgi_43_4290.png', slug: 'aztec-empire', title: 'Aztec Empire', category: 'slot', tags: ['aztec', 'adventure'], check: true },
  { src: 'imgi_44_4291.png', slug: 'panther-moon', title: 'Panther Moon', category: 'slot', tags: ['wild', 'free-spin'], rtp: 95.8 },
  { src: 'imgi_45_4292.png', slug: 'bonus-bears', title: 'Bonus Bears', category: 'slot', tags: ['bonus', 'free-spin'], rtp: 95.1 },
  { src: 'imgi_46_4205.png', slug: 'gold-monkey', title: 'Gold Monkey', category: 'slot', tags: ['asian', 'monkey'] },
  { src: 'imgi_47_4295.png', slug: 'fu-lu-shou', title: 'Fu Lu Shou', category: 'slot', tags: ['asian', 'angpao'], check: true },
  { src: 'imgi_48_4192.png', slug: 'highway-kings-pro', title: 'Highway Kings Pro', category: 'slot', tags: ['truck', 'classic'] },
  { src: 'imgi_49_4204.png', slug: 'dragons', title: 'Dragons', category: 'slot', tags: ['dragon', 'asian'] },
  { src: 'imgi_50_4194.png', slug: 'box-kings-treasure', title: "Box King's Treasure", category: 'slot', tags: ['treasure', 'adventure'] },
  { src: 'imgi_51_4209.png', slug: 'pirate-treasure', title: 'Pirate Treasure', category: 'slot', tags: ['pirate', 'adventure'], check: true },
  { src: 'imgi_52_4309.png', slug: 'magical-spin', title: 'Magical Spin', category: 'slot', tags: ['unicorn', 'fantasy'] },
  { src: 'imgi_53_4209.png', slug: 'top-gun', title: 'Top Gun', category: 'slot', tags: ['military', 'classic'] },
  { src: 'imgi_54_4287.png', slug: 'iceland', title: 'Iceland', category: 'slot', tags: ['ice', 'adventure'] },

  { src: 'imgi_55_4310.png', slug: 'green-light', title: 'Green Light', category: 'slot', tags: ['irish', 'lucky'] },
  { src: 'imgi_56_4320.png', slug: 'land-of-gold', title: 'Land of Gold', category: 'slot', tags: ['irish', 'lucky'] },
  { src: 'imgi_57_4245.png', slug: 'halloween-fortune-2', title: 'Halloween Fortune 2', category: 'slot', tags: ['halloween', 'holiday'] },
  { src: 'imgi_58_4218.png', slug: 'xun-cong-long', title: 'Xun Cong Long', category: 'slot', tags: ['asian', 'dragon'] },
  { src: 'imgi_59_4215.png', slug: 'desert-treasure', title: 'Desert Treasure', category: 'slot', tags: ['desert', 'adventure'], check: true },
  { src: 'imgi_60_4311.png', slug: 'safari-heat', title: 'Safari Heat', category: 'slot', tags: ['wild', 'jackpot'], rtp: 94.7 },
  { src: 'imgi_61_4207.png', slug: 'penguin-vacation', title: 'Penguin Vacation', category: 'slot', tags: ['penguin', 'fun'] },
  { src: 'imgi_62_4312.png', slug: 'cherry-love', title: 'Cherry Love', category: 'slot', tags: ['classic', 'fruit'] },
  { src: 'imgi_63_4231.png', slug: 'wild-girls', title: 'Wild Girls', category: 'slot', tags: ['anime', 'fun'], check: true },
  { src: 'imgi_64_4253.png', slug: 'football', title: 'Football', category: 'slot', tags: ['sports', 'soccer'] },
  { src: 'imgi_65_4346.png', slug: 'fu-huang-da-di', title: 'Fu Huang Da Di', category: 'slot', tags: ['asian', 'emperor'] },
  { src: 'imgi_66_4335.png', slug: 'zhao-cai-jin-bao', title: 'Zhao Cai Jin Bao', category: 'slot', tags: ['asian', 'angpao'] },
  { src: 'imgi_67_4225.png', slug: 'captains-treasure', title: "Captain's Treasure", category: 'slot', tags: ['pirate', 'free-spin'], rtp: 94.9 },
  { src: 'imgi_68_4213.png', slug: 'dragons-blue', title: 'Dragons (Blue)', category: 'slot', tags: ['dragon', 'ocean'] },
  { src: 'imgi_69_4248.png', slug: 'lucky-panda', title: 'Lucky Panda', category: 'slot', tags: ['asian', 'angpao'] },
  { src: 'imgi_70_4296.png', slug: 'triple-twister', title: 'Triple Twister', category: 'slot', tags: ['weather', 'big-win'] },
  { src: 'imgi_71_4203.png', slug: 'treasures-of-queen', title: 'Treasures of Queen', category: 'slot', tags: ['egypt', 'treasure'] },

  { src: 'imgi_72_4224.png', slug: 'epic-ape', title: 'Epic Ape', category: 'slot', tags: ['ape', 'wild'] },
  { src: 'imgi_73_4237.png', slug: 'tigers-claw', title: 'Tigers Claw', category: 'slot', tags: ['tiger', 'wild'] },
  { src: 'imgi_74_4208.png', slug: 'warriors-gold', title: 'Warriors Gold', category: 'slot', tags: ['warrior', 'asian'] },
  { src: 'imgi_75_4247.png', slug: 'lie-yan-zuanshi', title: 'Lie Yan Zuanshi', category: 'slot', tags: ['asian', 'diamond'] },
  { src: 'imgi_76_4254.png', slug: 'colossus-of-rhodes', title: 'Colossus of Rhodes', category: 'slot', tags: ['mythology', 'adventure'], check: true },
  { src: 'imgi_77_4263.png', slug: 'xuan-pu-man-huan', title: 'Xuan Pu Man Huan', category: 'slot', tags: ['asian', 'fantasy'], check: true },
  { src: 'imgi_78_4251.png', slug: 'cluck-cluck-chicken', title: 'Cluck Cluck Chicken', category: 'slot', tags: ['farm', 'fun'], check: true },
  { src: 'imgi_79_4268.png', slug: 'marilyn-monroe', title: 'Marilyn Monroe', category: 'slot', tags: ['celebrity', 'classic'] },
  { src: 'imgi_80_4252.png', slug: 'beach-life', title: 'Beach Life', category: 'slot', tags: ['beach', 'summer'] },
  { src: 'imgi_81_4270.png', slug: 'sultans-gold', title: "Sultan's Gold", category: 'slot', tags: ['arabian', 'treasure'] },
  { src: 'imgi_82_4273.png', slug: 'hologram-wilds', title: 'Hologram Wilds', category: 'slot', tags: ['futuristic', 'wild'] },
  { src: 'imgi_83_4264.png', slug: 'far-james-of-the-fox', title: 'Far James of the Fox', category: 'slot', tags: ['adventure', 'fox'], check: true },
  { src: 'imgi_84_4243.png', slug: 'ace-of-egypt', title: 'Ace of Egypt', category: 'slot', tags: ['egypt', 'mythology'] },
  { src: 'imgi_85_4280.png', slug: 'berry-berry-bonanza', title: 'Berry Berry Bonanza', category: 'slot', tags: ['fruit', 'bonus'] },
  { src: 'imgi_86_4281.png', slug: 'chinese-beauty', title: 'Chinese Beauty', category: 'slot', tags: ['asian', 'classic'], check: true },
  { src: 'imgi_87_4314.png', slug: 'crystal-waters', title: 'Crystal Waters', category: 'slot', tags: ['ocean', 'classic'] },
  { src: 'imgi_88_4255.png', slug: 'zhao-cai-tong-zi', title: 'Zhao Cai Tong Zi', category: 'slot', tags: ['asian', 'angpao'] },

  { src: 'imgi_89_4315.png', slug: 'sea-captain', title: 'Sea Captain', category: 'slot', tags: ['pirate', 'ocean'] },
  { src: 'imgi_90_4285.png', slug: 'sparta', title: 'Sparta', category: 'slot', tags: ['warrior', 'mythology'] },
  { src: 'imgi_91_4244.png', slug: 'lotto-madness', title: 'Lotto Madness', category: 'slot', tags: ['lottery', 'classic'] },
  { src: 'imgi_92_4279.png', slug: 'bombs-and-glory', title: 'Bombs and Glory', category: 'slot', tags: ['military', 'action'] },
  { src: 'imgi_93_4306.png', slug: 'stone-age', title: 'Stone Age', category: 'slot', tags: ['prehistoric', 'classic'] },
  { src: 'imgi_94_4283.png', slug: 'farmers-life', title: 'Farmers Life', category: 'slot', tags: ['farm', 'fun'], check: true },
  { src: 'imgi_95_4259.png', slug: 'orient-express', title: 'Orient Express', category: 'slot', tags: ['asian', 'travel'] },
  { src: 'imgi_96_4257.png', slug: 'a-night-out', title: 'A Night Out', category: 'slot', tags: ['party', 'classic'] },
  { src: 'imgi_97_4313.png', slug: 'pay-dirt', title: 'Pay Dirt', category: 'slot', tags: ['mining', 'western'] },
  { src: 'imgi_98_4226.png', slug: 'fei-long-zai-tian', title: 'Fei Long Zai Tian', category: 'slot', tags: ['asian', 'dragon'] },
  { src: 'imgi_99_4316.png', slug: 'shining-stars', title: 'Shining Stars', category: 'slot', tags: ['classic', 'stars'] },
  { src: 'imgi_100_4240.png', slug: 'si-xiang', title: 'Si Xiang', category: 'slot', tags: ['asian', 'mythology'] },
  { src: 'imgi_101_4265.png', slug: 'ranch-story', title: 'Ranch Story', category: 'slot', tags: ['western', 'farm'], check: true },
  { src: 'imgi_102_4274.png', slug: 'western-ranch', title: 'Western Ranch', category: 'slot', tags: ['western', 'farm'], check: true },
  { src: 'imgi_103_4284.png', slug: 'cowboy-cash', title: 'Cowboy Cash', category: 'slot', tags: ['western', 'money'], check: true },
  { src: 'imgi_104_4282.png', slug: 'cookie-pop', title: 'Cookie Pop', category: 'slot', tags: ['sweet', 'fun'] },
  { src: 'imgi_105_4317.png', slug: 'circus', title: 'Circus', category: 'slot', tags: ['circus', 'classic'] },

  { src: 'imgi_106_4230.png', slug: 'treasure-island', title: 'Treasure Island', category: 'slot', tags: ['pirate', 'treasure'] },
  { src: 'imgi_107_4271.png', slug: 'pirate-ship', title: 'Pirate Ship', category: 'slot', tags: ['pirate', 'adventure'] },
  { src: 'imgi_108_4318.png', slug: 'fairy-garden', title: 'Fairy Garden', category: 'slot', tags: ['fantasy', 'fairy'] },
  { src: 'imgi_109_4238.png', slug: 'the-discovery', title: 'The Discovery', category: 'slot', tags: ['columbus', 'adventure'] },
  { src: 'imgi_110_4227.png', slug: 'coyote-cash', title: 'Coyote Cash', category: 'slot', tags: ['western', 'money'] },
  { src: 'imgi_111_4319.png', slug: 't-rex', title: 'T-Rex', category: 'slot', tags: ['prehistoric', 'dinosaur'] },
  { src: 'imgi_112_4320.png', slug: 'bigshot', title: 'Bigshot', category: 'slot', tags: ['spy', 'classic'] },
  { src: 'imgi_113_4262.png', slug: 'banana-monkey', title: 'Banana Monkey', category: 'slot', tags: ['fun', 'monkey'] },
  { src: 'imgi_114_4239.png', slug: 'football-carnival', title: 'Football Carnival', category: 'slot', tags: ['sports', 'soccer'] },
  { src: 'imgi_115_4222.png', slug: 'queen-of-wands', title: 'Queen of Wands', category: 'slot', tags: ['fantasy', 'mythology'] },
  { src: 'imgi_116_4321.png', slug: 'sun-wukong', title: 'Sun Wukong', category: 'slot', tags: ['asian', 'monkey-king'] },
  { src: 'imgi_117_4322.png', slug: 'halloween-fortune', title: 'Halloween Fortune', category: 'slot', tags: ['halloween', 'holiday'] },
  { src: 'imgi_118_4323.png', slug: 'wealths-treasure', title: "Wealth's Treasure", category: 'slot', tags: ['asian', 'angpao'] },
  { src: 'imgi_119_4258.png', slug: 'great-ming-empire', title: 'Great Ming Empire', category: 'slot', tags: ['asian', 'dynasty'] },
  { src: 'imgi_120_4223.png', slug: 'niannian-youyu', title: 'Niannian Youyu', category: 'slot', tags: ['asian', 'angpao', 'fish'] },
  { src: 'imgi_121_4275.png', slug: 'wild-spirit', title: 'Wild Spirit', category: 'slot', tags: ['native', 'wild'] },
  { src: 'imgi_122_4266.png', slug: 'football-fans', title: 'Football Fans', category: 'slot', tags: ['sports', 'soccer'] },

  { src: 'imgi_123_4272.png', slug: 'funky-fruits-farm', title: 'Funky Fruits Farm', category: 'slot', tags: ['fruit', 'farm'] },
  { src: 'imgi_124_4324.png', slug: 'money-maven', title: 'Money Maven', category: 'slot', tags: ['money', 'classic'] },
  { src: 'imgi_125_4325.png', slug: 'fairy-garden-girls', title: 'Fairy Garden Girls', category: 'slot', tags: ['fantasy', 'fairy'] },
  { src: 'imgi_126_4277.png', slug: 'multi-game', title: 'Multi Game', category: 'slot', tags: ['variety', 'classic'] },
  { src: 'imgi_127_4261.png', slug: 'true-love', title: 'True Love', category: 'slot', tags: ['romance', 'classic'] },
  { src: 'imgi_128_4242.png', slug: 'santa-surprise', title: 'Santa Surprise', category: 'slot', tags: ['christmas', 'holiday'] },
  { src: 'imgi_129_4326.png', slug: 'aztecs-treasure', title: "Aztec's Treasure", category: 'slot', tags: ['aztec', 'treasure'] },
  { src: 'imgi_130_4278.png', slug: 'pyramid-of-ramesses', title: 'Pyramid of Ramesses', category: 'slot', tags: ['egypt', 'pyramid'] },
  { src: 'imgi_131_4276.png', slug: 'diamond-valley', title: 'Diamond Valley', category: 'slot', tags: ['gem', 'treasure'] },
  { src: 'imgi_132_4229.png', slug: 'riches-of-cleopatra', title: 'Riches of Cleopatra', category: 'slot', tags: ['egypt', 'queen'] },
  { src: 'imgi_133_4327.png', slug: 'rally', title: 'Rally', category: 'slot', tags: ['racing', 'sports'] },
  { src: 'imgi_134_4250.png', slug: 'sherlock-mystery', title: 'Sherlock Mystery', category: 'slot', tags: ['detective', 'adventure'] },
  { src: 'imgi_135_4217.png', slug: 'spud-reillys', title: "Spud O'Reilly's", category: 'slot', tags: ['irish', 'classic'] },
  { src: 'imgi_136_4256.png', slug: 'vital-temple', title: 'Vital Temple', category: 'slot', tags: ['temple', 'adventure'] },
  { src: 'imgi_137_4241.png', slug: 'pharaohs-secrets', title: "Pharaoh's Secrets", category: 'slot', tags: ['egypt', 'mystery'] },
  { src: 'imgi_138_4228.png', slug: 'feicui-gong-zhu', title: 'Feicui Gong Zhu', category: 'slot', tags: ['asian', 'princess'] },
  { src: 'imgi_139_4216.png', slug: 'geishas-garden', title: "Geisha's Garden", category: 'slot', tags: ['asian', 'classic'] },

  { src: 'imgi_140_4328.png', slug: 'silver-bullet', title: 'Silver Bullet', category: 'slot', tags: ['western', 'classic'] },
  { src: 'imgi_141_4267.png', slug: 'dolphin', title: 'Dolphin', category: 'slot', tags: ['ocean', 'classic'] },
  { src: 'imgi_142_4329.png', slug: 'traffic-surprise', title: 'Traffic Surprise', category: 'slot', tags: ['city', 'fun'], check: true },
  { src: 'imgi_143_4260.png', slug: 'seasons-greetings', title: "Seasons Greetings", category: 'slot', tags: ['christmas', 'holiday'] },
  { src: 'imgi_144_4269.png', slug: 'xin-pan-jin-lian', title: 'Xin Pan Jin Lian', category: 'slot', tags: ['asian', 'classic'] },
  { src: 'imgi_145_4330.png', slug: 'feng-lin', title: 'Feng Lin', category: 'slot', tags: ['asian', 'wind'], check: true },
  { src: 'imgi_146_4303.png', slug: 'shui-hu-zhuan', title: 'Shui Hu Zhuan', category: 'slot', tags: ['asian', 'classic'] },
  { src: 'imgi_147_4304.png', slug: 'silent-samurai', title: 'Silent Samurai', category: 'slot', tags: ['samurai', 'japan'] },
  { src: 'imgi_148_4232.png', slug: 'chinese-temple', title: 'Chinese Temple', category: 'slot', tags: ['asian', 'temple'], check: true },
  { src: 'imgi_149_4219.png', slug: 'spartan', title: 'Spartan', category: 'slot', tags: ['warrior', 'mythology'] },
  { src: 'imgi_150_4236.png', slug: 'rina-cinni', title: 'Rina Cinni', category: 'slot', tags: ['action', 'girl'], check: true },
  { src: 'imgi_151_4234.png', slug: 'amazon-jungle', title: 'Amazon Jungle', category: 'slot', tags: ['jungle', 'adventure'] },
  { src: 'imgi_152_4331.png', slug: 'video-king', title: 'Video King', category: 'slot', tags: ['tv', 'classic'], check: true },
  { src: 'imgi_153_4332.png', slug: 'tally-ho', title: 'Tally Ho', category: 'slot', tags: ['british', 'hunt'] },
  { src: 'imgi_154_4305.png', slug: 'jin-qian-wa', title: 'Jin Qian Wa', category: 'slot', tags: ['asian', 'angpao'] },
  { src: 'imgi_155_4333.png', slug: 'dragon-goddess', title: 'Dragon Goddess', category: 'slot', tags: ['dragon', 'mythology'] },
  { src: 'imgi_156_4334.png', slug: 'wu-fu-men', title: 'Wu Fu Men', category: 'slot', tags: ['asian', 'fortune'] },

  { src: 'imgi_157_4335.png', slug: 'aladdin', title: 'Aladdin', category: 'slot', tags: ['arabian', 'genie'] },
  { src: 'imgi_158_4336.png', slug: 'alice', title: 'Alice', category: 'slot', tags: ['fantasy', 'wonderland'] },
  { src: 'imgi_159_4210.png', slug: 'thai-paradise', title: 'Thai Paradise', category: 'slot', tags: ['thai', 'free-spin'], rtp: 95.4 },
  { src: 'imgi_160_4337.png', slug: 'laura', title: 'Laura', category: 'slot', tags: ['adventure', 'tomb'] },
  { src: 'imgi_161_4338.png', slug: 'pirate', title: 'Pirate', category: 'slot', tags: ['pirate', 'adventure'] },
  { src: 'imgi_162_4339.png', slug: 'key-of-luck', title: 'Key of Luck', category: 'slot', tags: ['asian', 'fortune'] },
  { src: 'imgi_163_4340.png', slug: 'fortune-panda', title: 'Fortune Panda', category: 'slot', tags: ['asian', 'angpao'], rtp: 96.8 },
  { src: 'imgi_164_4341.png', slug: 'golden-lotus', title: 'Golden Lotus', category: 'slot', tags: ['asian', 'flower'] },
  { src: 'imgi_165_4212.png', slug: 'big-prosperity', title: 'Big Prosperity', category: 'slot', tags: ['asian', 'angpao'] },
  { src: 'imgi_166_4221.png', slug: 'wong-choy', title: 'Wong Choy', category: 'slot', tags: ['angpao', 'jackpot'], rtp: 96.2 },
  { src: 'imgi_167_4198.png', slug: 'strip-poker-night', title: 'Strip Poker Night', category: 'slot', tags: ['poker', 'adult'] },
  { src: 'imgi_168_4342.png', slug: 'nihon-seven', title: 'Nihon Seven', category: 'slot', tags: ['japan', 'classic'], check: true },
  { src: 'imgi_169_4202.png', slug: 'kill-five-rates', title: 'Kill Five Rates', category: 'slot', tags: ['asian', 'classic'], check: true },
  { src: 'imgi_170_4306.png', slug: 'gao-fu-shuai', title: 'Gao Fu Shuai', category: 'slot', tags: ['asian', 'rich'], check: true },
  { src: 'imgi_171_4307.png', slug: 'wild-fox', title: 'Wild Fox', category: 'slot', tags: ['fox', 'wild'] },
  { src: 'imgi_172_4293.png', slug: 'amazing-image', title: 'Amazing Image', category: 'slot', tags: ['classic', 'mystery'], check: true },
  { src: 'imgi_173_4343.png', slug: 'indian-myth', title: 'Indian Myth', category: 'slot', tags: ['indian', 'mythology'] },

  { src: 'imgi_174_4344.png', slug: 'zhonghua-zhi-hun', title: 'Zhonghua Zhi Hun', category: 'slot', tags: ['asian', 'patriotic'] },
  { src: 'imgi_175_4345.png', slug: 'african-wildlife', title: 'African Wildlife', category: 'slot', tags: ['safari', 'wild'] },

  // Live casino games (category: live)
  { src: 'imgi_176_3018.png', slug: 'baccarat', title: 'Baccarat', category: 'live', tags: ['table', 'live'], rtp: 98.9 },
  { src: 'imgi_177_3019.png', slug: 'single-pick', title: 'Single Pick', category: 'live', tags: ['table', 'live'], check: true },
  { src: 'imgi_178_3020.png', slug: 'blackjack', title: 'Blackjack', category: 'live', tags: ['table', 'live'] },
  { src: 'imgi_179_3021.png', slug: 'roulette-2', title: 'Roulette 2', category: 'live', tags: ['table', 'live'] },
  { src: 'imgi_180_3022.png', slug: 'roulette-3d', title: 'Roulette 3D', category: 'live', tags: ['table', 'live'] },
  { src: 'imgi_181_3023.png', slug: 'roulette-4', title: 'Roulette 4', category: 'live', tags: ['table', 'live'] },
  { src: 'imgi_182_3024.png', slug: 'roulette-5', title: 'Roulette 5', category: 'live', tags: ['table', 'live'] },
  { src: 'imgi_183_3025.png', slug: 'poker-three', title: 'Poker Three', category: 'live', tags: ['table', 'live'] },
  { src: 'imgi_184_3026.png', slug: 'holdem', title: "Hold'em", category: 'live', tags: ['table', 'live'] },
  { src: 'imgi_185_3027.png', slug: 'casino-war', title: 'Casino War', category: 'live', tags: ['table', 'live'] },
  { src: 'imgi_186_3029.png', slug: 'dragon-tiger', title: 'Dragon Tiger', category: 'live', tags: ['table', 'live'], rtp: 96.3 },
  { src: 'imgi_187_3028.png', slug: 'dragon-tiger-2', title: 'Dragon Tiger 2', category: 'live', tags: ['table', 'live'] },
  { src: 'imgi_188_3030.png', slug: 'dragon-x', title: 'Dragon X', category: 'live', tags: ['table', 'live'], check: true },
  { src: 'imgi_189_3031.png', slug: 'sicbo', title: 'Sic Bo', category: 'live', tags: ['dice', 'live'] },
  { src: 'imgi_190_3032.png', slug: 'hi-lo', title: 'Hi Lo', category: 'live', tags: ['dice', 'live'] },

  { src: 'imgi_191_3033.png', slug: 'bingo-real', title: 'Bingo Real', category: 'live', tags: ['bingo', 'live'] },
  { src: 'imgi_192_3034.png', slug: 'animal-band', title: 'Animal Band', category: 'slot', tags: ['animal', 'music'] },
  { src: 'imgi_193_3035.png', slug: 'lion-dance', title: 'Lion Dance', category: 'slot', tags: ['asian', 'festival'], check: true },
  { src: 'imgi_194_3036.png', slug: 'coin-master', title: 'Coin Master', category: 'slot', tags: ['money', 'classic'], check: true },
  { src: 'imgi_195_3037.png', slug: 'super-speed', title: 'Super Speed', category: 'slot', tags: ['racing', 'sports'] },
  { src: 'imgi_196_3038.png', slug: 'king-derby-plus', title: 'King Derby Plus', category: 'slot', tags: ['horse', 'racing'] },
  { src: 'imgi_197_3039.png', slug: 'monkey-pole', title: 'Monkey Pole', category: 'slot', tags: ['monkey', 'fun'], check: true },
  { src: 'imgi_198_3040.png', slug: 'thunder-bolt', title: 'Thunder Bolt', category: 'slot', tags: ['weather', 'action'] },
  { src: 'imgi_199_3041.png', slug: 'king-derby', title: 'King Derby', category: 'slot', tags: ['horse', 'racing'] },
  { src: 'imgi_200_3042.png', slug: 'motor-bike', title: 'Motor Bike', category: 'slot', tags: ['racing', 'sports'] },
  { src: 'imgi_201_2017.png', slug: 'roulette-50', title: 'Roulette 50', category: 'live', tags: ['table', 'live'] },
  { src: 'imgi_202_2018.png', slug: 'baccarat-2', title: 'Baccarat 2', category: 'live', tags: ['table', 'live'] },
  { src: 'imgi_203_2019.png', slug: 'sicbo-2', title: 'Sic Bo 2', category: 'live', tags: ['dice', 'live'] },
  { src: 'imgi_204_2020.png', slug: 'dragon-slot', title: 'Dragon Slot', category: 'slot', tags: ['dragon', 'classic'], check: true },
  { src: 'imgi_205_2021.png', slug: 'bull-fight', title: 'Bull Fight', category: 'slot', tags: ['bull', 'action'] },
  { src: 'imgi_206_2022.png', slug: 'super-speed-2', title: 'Super Speed 2', category: 'slot', tags: ['racing', 'sports'] },
  { src: 'imgi_207_2023.png', slug: 'chinese-festival', title: 'Chinese Festival', category: 'slot', tags: ['asian', 'festival'], check: true },

  { src: 'imgi_208_2024.png', slug: 'fortune-monkey', title: 'Fortune Monkey', category: 'slot', tags: ['monkey', 'asian'] },
  { src: 'imgi_209_2025.png', slug: 'animal-band-2', title: 'Animal Band 2', category: 'slot', tags: ['animal', 'music'] },
  { src: 'imgi_210_2026.png', slug: 'single-pick-2', title: 'Single Pick 2', category: 'live', tags: ['table', 'live'] },

  // Fish shooters (category: fish)
  { src: 'imgi_211_1009.png', slug: 'fishing-star', title: 'Fishing Star', category: 'fish', tags: ['fish', 'shooter'] },
  { src: 'imgi_212_1004.png', slug: 'lucky-monkey', title: 'Lucky Monkey', category: 'fish', tags: ['fish', 'shooter'], check: true },
  { src: 'imgi_213_1013.png', slug: 'phoenix-fish', title: 'Phoenix Fish', category: 'fish', tags: ['fish', 'shooter'], check: true },
  { src: 'imgi_214_1002.png', slug: 'wu-kong-fish', title: 'Wu Kong Fish', category: 'fish', tags: ['fish', 'shooter'], check: true },
  { src: 'imgi_215_1001.png', slug: 'ocean-fish', title: 'Ocean Fish', category: 'fish', tags: ['fish', 'shooter'], check: true },
];
